github:
  is_project_page: false 
  is_user_page: false
  public: false 
  repository_url: http://linkedin.com/in/mjliu 
  
show_downloads: false

author:
  name: M.J.
  url: http://mjliu.com
  
theme: jekyll-theme-tactile 
title: M.
description: Simplicity is the ultimate sophistication.

google_analytics: UA-50968899-1
facebook: mjliu
linkedin: mjliu
twitter: tigerplusdragon
instagram: tigerplusdragon
github: mikexl
